Repository trustbloc/sandbox, pull requests merged in 2020-08, with the labels that each got.

#447 feat: Support to Configure Issuer Adapters
  cmd/issuer-rest/static/index.html
  cmd/issuer-rest/static/js/action.js
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
Labels: cla-signed

#448 feat: Add driving license skin in strapi
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#452 refactor: Update CreditCardStatement data config to use new context
  test/bdd/fixtures/demo/adapter-config/rp/presentationdefinitions.json
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#453 feat: Update edge-agent and EDV images
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#454 feat: Create Driving License Homepage
  cmd/issuer-rest/startcmd/start.go
  cmd/issuer-rest/static/drivinglicense.html
  cmd/issuer-rest/static/js/action.js
  cmd/issuer-rest/static/js/profile.js
  test/bdd/fixtures/oathkeeper/config.yaml
  test/bdd/fixtures/oathkeeper/rules/resource-server-template.json
  test/bdd/fixtures/scripts/hydra_configure.sh
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#455 fix: DL data setup
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#456 chore: Update Adapter and Wallet with OOB support for DIDComm
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#459 fix: Update DID Key resolver config
  test/bdd/fixtures/demo/docker-compose-universal-resolver.yml
  test/bdd/fixtures/universal-resolver/config.json
Labels: cla-signed

#458 feat: Create Credit Score Homepage
  cmd/issuer-rest/startcmd/start.go
  cmd/issuer-rest/static/creditscore.html
  cmd/issuer-rest/static/js/action.js
  test/bdd/fixtures/oathkeeper/config.yaml
  test/bdd/fixtures/oathkeeper/rules/resource-server-template.json
  test/bdd/fixtures/scripts/hydra_configure.sh
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#461 chore: Small fixes for demo
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/restclient/sender.go
Labels: cla-signed

#460 chore: Update adapter images - Support for RP scopes configuration
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/scripts/rp-rest_start.sh
Labels: cla-signed

#464 feat: Add governance vcs
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
Labels: cla-signed

#466 refactor: Issuer User Data API
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#469 fix: strapi docker version update
  test/bdd/fixtures/demo/docker-compose-third-party.yml
Labels: cla-signed

#472 feat: Add bank account homepage
  cmd/rp-rest/startcmd/start.go
  cmd/rp-rest/static/bankaccount.html
Labels: cla-signed

#474 refactor: Use mDL context for DL demo
  cmd/issuer-rest/static/js/action.js
  cmd/rp-rest/static/bankaccount.html
  test/bdd/fixtures/oathkeeper/config.yaml
  test/bdd/fixtures/oathkeeper/rules/resource-server-template.json
  test/bdd/fixtures/scripts/hydra_configure.sh
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#470 feat: update rp-adapter
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/adapter-config/rp/presentationdefinitions.json
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
Labels: cla-signed

#475 chore: Credit Score data setup
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#476 chore: Update dependencies and images
  cmd/issuer-rest/go.mod
  cmd/issuer-rest/go.sum
  cmd/rp-rest/go.mod
  cmd/rp-rest/go.sum
  go.mod
  go.sum
  pkg/restapi/issuer/operation/operations.go
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#477 refactor: mDL context url update
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#478 refactor: Remove issuer profile selection for DIDComm demo
  cmd/issuer-rest/static/index.html
  cmd/issuer-rest/static/js/action.js
  docs/demo/sandbox_didcomm_playground.md
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
Labels: cla-signed

#479 feat: VP update response page and error handling
  cmd/rp-rest/static/bankaccount.html
  cmd/rp-rest/static/img/failed.svg
  cmd/rp-rest/static/img/oops.png
  cmd/rp-rest/static/img/success.png
  cmd/rp-rest/static/vp.html
  pkg/restapi/rp/operation/operations.go
Labels: cla-signed

#481 docs: updated prerequisites in README
  docs/demo/build.md
Labels: cla-signed, documentation

#483 feat: Upgrade driiving license flow to didcomm
  cmd/issuer-rest/static/drivinglicense.html
  cmd/issuer-rest/static/js/action.js
Labels: cla-signed

#485 feat: Update credit score flow to didcomm
  cmd/issuer-rest/static/creditscore.html
  cmd/issuer-rest/static/js/action.js
Labels: cla-signed

#490 feat: Upgrade Bank Account to DIDComm Flow
  cmd/issuer-rest/static/js/action.js
  cmd/rp-rest/static/bankaccount.html
  cmd/rp-rest/static/css/assets/css/style.css
  cmd/rp-rest/static/css/bootstrap.css
  cmd/rp-rest/static/css/bootstrap.min.css
  cmd/rp-rest/static/css/prettyPhoto.css
  cmd/rp-rest/static/css/style.css
  cmd/rp-rest/static/index.html
  cmd/rp-rest/static/vp.html
  test/bdd/fixtures/demo/adapter-config/rp/presentationdefinitions.json
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
  test/bdd/fixtures/scripts/rp-rest_start.sh
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#491 chore: Update Issuer adapter docker
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#492 chore: update to latest sidetree-fabric, sidetree-mock
  Makefile
  scripts/generate_test_keys.sh
  test/bdd/features/setupfabric.feature
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-sidetree-fabric.yml
  test/bdd/fixtures/fabric/config/configtx.yaml
  test/bdd/fixtures/fabric/config/ledger/did-sidetree-protocol-v1_0.json
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/offledger_steps.go
Labels: cla-signed

#498 feat: demo of mixed local+remote credentials
  cmd/issuer-rest/static/creditscore.html
  cmd/issuer-rest/static/drivinglicense.html
  cmd/issuer-rest/static/js/action.js
  cmd/rp-rest/static/bankaccount.html
  pkg/restapi/rp/operation/operations.go
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
  test/bdd/fixtures/scripts/rp-rest_start.sh
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed, didcomm, enhancement

#501 chore: configure governance vcs
  go.mod
  go.sum
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/governance/governance_claims.json
  test/bdd/fixtures/scripts/vcs/governance-trustbloc-profiles.sh
  test/bdd/fixtures/scripts/vcs_governance_configure.sh
Labels: cla-signed

#504 chore: Update User Agent and Wallet docker versions
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#505 feat: UI theme update and edge-adapter update
  cmd/issuer-rest/go.sum
  cmd/issuer-rest/static/creditscore.html
  cmd/issuer-rest/static/css/layout.css
  cmd/issuer-rest/static/didAuth.html
  cmd/issuer-rest/static/didcomm.html
  cmd/issuer-rest/static/drivinglicense.html
  cmd/issuer-rest/static/img/background.jpg
  cmd/issuer-rest/static/index.html
  cmd/issuer-rest/static/receiveVC.html
  cmd/issuer-rest/static/vc.html
  cmd/login-consent-server/templates/consent.html
  cmd/login-consent-server/templates/login.html
  cmd/rp-rest/go.sum
  cmd/rp-rest/static/bankaccount.html
  cmd/rp-rest/static/img/failed.png
  cmd/rp-rest/static/img/failed.svg
  cmd/rp-rest/static/vp.html
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#508 fix: #506 incorrect DL data setup
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: bug, cla-signed

#507 chore: update sidetree-fabric image
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#512 chore: update vcs image
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/scripts/run-uni-resolver-web.sh
Labels: cla-signed

#515 feat: #510 rp-adapter updates
  test/bdd/fixtures/demo/.env
Labels: cla-signed, enhancement, rp adapter

#514 feat: Support for Drivers Licence + Evidence Credential
  cmd/issuer-rest/static/drivinglicense.html
  cmd/issuer-rest/static/js/action.js
  cmd/rp-rest/static/bankaccount.html
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
  test/bdd/fixtures/scripts/rp-rest_start.sh
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#516 docs: Non DIDComm demo component diagram
  docs/demo/nondidcomm_component_diagram.svg
Labels: cla-signed

#517 docs: Update non-didcomm component diagram
  README.md
  docs/demo/nondidcomm_component_diagram.svg
Labels: cla-signed

#518 docs: DIDComm demo component diagram
  README.md
  docs/demo/didcomm_component_diagram.svg
Labels: cla-signed

#511 feat: Add friendly name for cms scope and minor UI fix
  cmd/issuer-rest/static/creditscore.html
  cmd/issuer-rest/static/didAuth.html
  cmd/issuer-rest/static/drivinglicense.html
  cmd/issuer-rest/static/index.html
  cmd/issuer-rest/static/receiveVC.html
  cmd/login-consent-server/templates/consent.html
  cmd/rp-rest/static/index.html
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#519 chore: Update credit score report and DL data setup to match each other (name/dob)
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#520 fix: Setting Default loading icon display to none
  cmd/rp-rest/static/index.html
Labels: cla-signed

#521 chore: update sideetree-mock and sidetre-fabric to 0.1.4
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#522 feat: Support to configure Assurance data
  cmd/issuer-rest/static/drivinglicense.html
  cmd/issuer-rest/static/js/action.js
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/fixtures/oathkeeper/config.yaml
  test/bdd/fixtures/oathkeeper/rules/resource-server-template.json
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#523 docs: Update chapi+vc services demo component diagram
  docs/demo/nondidcomm_component_diagram.svg
Labels: cla-signed

#524 chore: configure couchdb transient storage for rp.example.com
  cmd/common/common.go
  cmd/common/common_test.go
  cmd/issuer-rest/go.sum
  cmd/issuer-rest/startcmd/start.go
  cmd/issuer-rest/startcmd/start_test.go
  cmd/rp-rest/go.mod
  cmd/rp-rest/go.sum
  cmd/rp-rest/startcmd/start.go
  cmd/rp-rest/startcmd/start_test.go
  go.mod
  go.sum
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
Labels: chore, cla-signed

#525 docs: Update DIDComm component diagram
  docs/demo/nondidcomm_component_diagram.svg
Labels: cla-signed

#526 chore: update to latest edge-agent and trustbloc-did-method
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#527 docs: Update demo name and component diagrams
  README.md
  docs/demo/didcomm_component_diagram.svg
  docs/demo/nondidcomm_component_diagram.svg
  docs/demo/sandbox_adapter_playground.md
  docs/demo/sandbox_vcs_playground.md
  docs/images/adapter_component_diagram.svg
  docs/images/vcs_component_diagram.svg
Labels: cla-signed

#528 chore: Update edge-agent image, disable edge-agent SDS storage
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#529 chore: Add profile for Credit Report issuer (Move out of CC Issuer)
  cmd/issuer-rest/static/js/action.js
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
Labels: cla-signed

#530 feat: Add preview and source for VP data in RP and Minor UI fix
  cmd/login-consent-server/templates/login.html
  cmd/rp-rest/startcmd/start.go
  cmd/rp-rest/static/bankaccount.html
  cmd/rp-rest/static/didcommvp.html
  cmd/rp-rest/static/img/logo.png
  cmd/rp-rest/static/index.html
  cmd/rp-rest/static/vp.html
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#531 fix: Upgrade password to avoid checker warning
  cmd/login-consent-server/templates/login.html
Labels: cla-signed

#532 docs: Update VCS db component to show mysql/couchdb support
  docs/images/vcs_component_diagram.svg
Labels: cla-signed

#533 docs: Update governance service to show support for couchdb/mysql
  docs/images/adapter_component_diagram.svg
Labels: cla-signed

#534 chore: update to latest user agent and issuer adapter
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/governance/governance_claims.json
Labels: cla-signed

#535 chore: update to latest edge-agent
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#537 docs: New Bank Account use case
  README.md
  docs/demo/new-bank-account-usecase.md
Labels: cla-signed

#538 chore: add kms rest image
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
Labels: cla-signed

#541 refactor: Governance Framework name/desc and bank account use case demo link update
  docs/demo/new-bank-account-usecase.md
  test/bdd/fixtures/governance/governance_claims.json
Labels: cla-signed

#540 feat: Add success page
  cmd/rp-rest/startcmd/start.go
  cmd/rp-rest/static/bankaccount.html
  cmd/rp-rest/static/didcommvp.html
  cmd/rp-rest/static/img/bank_account.jpg
  cmd/rp-rest/static/success.html
Labels: cla-signed
