Repository trustbloc/sandbox, pull requests merged in 2020-07, with the labels that each got.

#395 feat: Command line parameter for setting default logging level
  cmd/common/common.go
  cmd/common/common_test.go
  cmd/issuer-rest/startcmd/start.go
  cmd/issuer-rest/startcmd/start_test.go
  cmd/rp-rest/startcmd/start.go
  cmd/rp-rest/startcmd/start_test.go
Labels: cla-signed

#396 feat: Endpoints for changing/retrieving logging level on the fly
  cmd/issuer-rest/go.mod
  cmd/issuer-rest/go.sum
  cmd/issuer-rest/startcmd/start.go
  cmd/login-consent-server/go.mod
  cmd/login-consent-server/go.sum
  cmd/rp-rest/go.mod
  cmd/rp-rest/go.sum
  cmd/rp-rest/startcmd/start.go
  go.mod
  go.sum
Labels: cla-signed

#400 feat: #397 install rp adapter components
  images/rp-rest/Dockerfile
  scripts/sandbox_stop.sh
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/adapter-config/rp/presentationdefinitions.json
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/scripts/mysql/mysql_configure.sql
  test/bdd/fixtures/scripts/rp-rest_start.sh
Labels: cla-signed, didcomm, enhancement, rp adapter

#401 chore: Update Issuer adapter version and setup script
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
Labels: cla-signed

#403 feat: #399 didcomm demo: oauth2 config for rp.example.com
  cmd/issuer-rest/go.sum
  cmd/rp-rest/go.mod
  cmd/rp-rest/go.sum
  cmd/rp-rest/startcmd/start.go
  cmd/rp-rest/startcmd/start_test.go
  cmd/rp-rest/static/index.html
  go.mod
  go.sum
  pkg/restapi/rp/controller.go
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/scripts/rp-rest_start.sh
Labels: cla-signed

#405 chore: Issuer adapter version update
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
Labels: cla-signed

#407 feat: DIDComm Credential API for Issuer Adapter
  cmd/issuer-rest/startcmd/start.go
  cmd/issuer-rest/static/index.html
  pkg/restapi/issuer/controller.go
  pkg/restapi/issuer/controller_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#409 chore: update to latest user agent
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#410 fix: rp.example.com not starting
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#411 feat: #494 didcomm demo: oauth2 callback endpoint for rp-rest
  cmd/issuer-rest/go.sum
  cmd/rp-rest/go.sum
  cmd/rp-rest/startcmd/start.go
  cmd/rp-rest/static/index.html
  go.mod
  go.sum
  pkg/restapi/rp/controller_test.go
  pkg/restapi/rp/operation/operations.go
  pkg/restapi/rp/operation/operations_test.go
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/scripts/rp-rest_start.sh
Labels: cla-signed, didcomm, enhancement, rp adapter

#413 feat: Update Issuer Adapter and Edge agent versions
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
Labels: cla-signed

#415 chore: Update EDV image version
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#416 chore: #412 didcomm demo: update rp-adapter image
  docs/demo/build.md
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/adapter-config/rp/presentationdefinitions.json
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/scripts/rp-rest_start.sh
Labels: chore, cla-signed, didcomm, rp adapter

#417 feat: Support to Configure database
  cmd/issuer-rest/go.sum
  cmd/issuer-rest/startcmd/start.go
  cmd/issuer-rest/startcmd/start_test.go
  go.sum
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
Labels: cla-signed

#418 fix: Update dns name for issuer/rp adapter
  cmd/rp-rest/static/index.html
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
Labels: cla-signed

#420 chore: Update issuer adapter version
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
Labels: cla-signed

#421 chore: Update issuer adapter with tls support
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
Labels: cla-signed

#423 fix: #422 didcomm demo: rp.example.com and rp-adapter: various fixes
  pkg/restapi/rp/operation/operations.go
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
  test/bdd/fixtures/scripts/rp-rest_start.sh
Labels: bug, cla-signed, didcomm, rp adapter

#428 chore: Update Issuer Adapter docker version
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#429 fix: RP page title
  cmd/rp-rest/static/vp.html
Labels: cla-signed

#432 feat: Issuer UI - Show options to choose the Demo (DIDComm/NonDIDComm)
  cmd/issuer-rest/static/index.html
  cmd/issuer-rest/static/js/action.js
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#431 fix: rp-adapter ui
  test/bdd/fixtures/demo/.env
Labels: bug, cla-signed, didcomm, rp adapter

#433 chore: Issuer Adapter docker update
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#435 docs: DIDComm Demo steps
  README.md
  docs/demo/sandbox_didcomm_playground.md
  docs/demo/sandbox_nondidcomm_playground.md
Labels: cla-signed

#437 docs: Update README summary section
  README.md
Labels: cla-signed

#438 feat: update to latest wallet & adapters
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/scripts/mysql/mysql_configure.sql
Labels: cla-signed

#440 chore: Update Issuer/RP adapter and Web wallet to pull ConsentCred to AuthzCred changes
  test/bdd/fixtures/demo/.env
Labels: cla-signed
