Repository trustbloc/sandbox, pull requests merged in 2020-11, with the labels that each got.

#629 chore: update demo images
  cmd/issuer-rest/go.mod
  cmd/rp-rest/go.mod
  go.mod
  go.sum
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#630 chore: update to Go 1.15
  Makefile
  ci/azure-pipelines.yml
  cmd/common/common.go
  cmd/issuer-rest/go.mod
  cmd/login-consent-server/go.mod
  cmd/rp-rest/go.mod
  docs/demo/build.md
  go.mod
  test/bdd/go.mod
Labels: cla-signed

#631 chore: update golangci-lint to v1.31
  .golangci.yml
  cmd/common/common_test.go
  cmd/issuer-rest/main_test.go
  cmd/issuer-rest/startcmd/start.go
  cmd/login-consent-server/main.go
  cmd/login-consent-server/main_test.go
  cmd/rp-rest/main_test.go
  cmd/rp-rest/startcmd/start.go
  pkg/restapi/internal/common/oidc/oidc.go
  pkg/restapi/internal/common/oidc/oidc_test.go
  pkg/restapi/issuer/operation/operations.go
  pkg/restapi/issuer/operation/operations_test.go
  pkg/restapi/rp/operation/operations_test.go
  pkg/token/issuer/issuer_test.go
  pkg/token/resolver/resolver_test.go
  scripts/check_lint.sh
  test/bdd/fabriccli_steps.go
Labels: cla-signed

#633 chore: Blinded RP Integration
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#634 chore: Update adapter image tag (Support to configure blinded routing)
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
Labels: cla-signed

#635 chore: Update sidetree, fabric, did-method etc.
  Makefile
  cmd/issuer-rest/go.mod
  cmd/issuer-rest/go.sum
  cmd/login-consent-server/go.mod
  cmd/login-consent-server/go.sum
  cmd/rp-rest/go.mod
  cmd/rp-rest/go.sum
  go.mod
  go.sum
  test/bdd/features/setupfabric.feature
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/fabric/config/ledger/did-sidetree-protocol-v0_1.json
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#636 chore: update demo images
  Makefile
  go.mod
  go.sum
  scripts/sandbox_start.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/discovery-config/sidetree-fabric/generate_did_method_config_fabric.sh
Labels: cla-signed

#637 fix: CrudeProductCredential context
  test/bdd/fixtures/scripts/strapi_configure.sh
Labels: cla-signed

#638 chore: Adapter docker update
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
  test/bdd/fixtures/scripts/rp-rest_start.sh
Labels: cla-signed

#639 chore: update edge-service and edv versions
  go.mod
  go.sum
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#640 chore: Update hub-router and edge-adapter docker images
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#641 chore: update demo images
  cmd/issuer-rest/go.mod
  cmd/issuer-rest/go.sum
  cmd/rp-rest/go.mod
  cmd/rp-rest/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-universal-resolver.yml
Labels: cla-signed

#642 chore: update user agent image
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#643 chore: update user-agent image
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#644 chore: update demo images
  Makefile
  go.mod
  go.sum
  test/bdd/features/setupfabric.feature
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/fabric/config/ledger/did-sidetree-protocol-v0_1.json
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
  test/bdd/fixtures/scripts/vcs/governance-trustbloc-profiles.sh
  test/bdd/fixtures/scripts/vcs/holder-trustbloc-profiles.sh
  test/bdd/fixtures/scripts/vcs/holder-vendor-profiles.sh
  test/bdd/fixtures/scripts/vcs/issuer-interop-profiles.sh
  test/bdd/fixtures/scripts/vcs/issuer-trustbloc-profiles.sh
  test/bdd/fixtures/scripts/vcs/issuer-vendor-profiles.sh
  test/bdd/fixtures/scripts/vcs_verifier_configure.sh
Labels: cla-signed

#645 chore: Hub-router docker update
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#646 feat: wallet oidc login via hub-auth
  cmd/login-consent-server/main.go
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-didcomm.yml
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/scripts/hydra/auth-rest-hydra_configure.sh
  test/bdd/fixtures/scripts/hydra/hydra_configure.sh
  test/bdd/fixtures/scripts/mysql/mysql_configure.sql
Labels: cla-signed

#648 chore: update demo images
  Makefile
  go.mod
  go.sum
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-sidetree-mock.yml
  test/bdd/fixtures/discovery-config/sidetree-fabric/config-data/testnet.trustbloc.local.json
  test/bdd/fixtures/discovery-config/sidetree-mock/config-data/testnet.trustbloc.local.json
  test/bdd/fixtures/fabric/config/ledger/did-sidetree-config.json
  test/bdd/fixtures/fabric/config/ledger/mychannel-consortium-config.json
Labels: cla-signed

#650 fix: Create Bank brand rather than issuer for the wallet login screen
  cmd/login-consent-server/main.go
  cmd/login-consent-server/main_test.go
  cmd/login-consent-server/templates/bankconsent.html
  cmd/login-consent-server/templates/banklogin.html
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#651 chore: Adapter docker update
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#653 chore: update edge-agent docker image
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#654 feat: Wallet - AuthZ KMS integration
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
Labels: cla-signed

#656 feat: Wallet - OpsKMS/KeySDS server integration
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
Labels: cla-signed

#657 chore: Use couchdb in authz and ops key server
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#658 chore: Update user agent docker image
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#659 feat: hub-auth updates
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/auth-rest-config/oidc-providers.yaml
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed, enhancement

#660 chore: Updates edge-agent revision
  docs/demo/build.md
  docs/demo/new-bank-account-usecase.md
  docs/demo/register-property-usecase.md
  docs/demo/sandbox_adapter_playground.md
  docs/demo/sandbox_vcs_playground.md
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/scripts/hydra/auth-rest-hydra_configure.sh
Labels: cla-signed

#661 feat: Update edge-agent and edv images
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#662 fix: Changes domain (myagent.support)
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/scripts/hydra/auth-rest-hydra_configure.sh
Labels: cla-signed

#663 fix: Fixes demo for linux.
  scripts/sandbox_start.sh
Labels: cla-signed

#664 chore: Update wallet, hub-kms and hub-auth dependency
  scripts/generate_test_keys.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#665 chore: Update wallet-web and wallet-server docker version
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#666 chore: Update edge adapter, edge agent, hub-kms and hub-router docker images
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#667 feat: Use EDV storage for web-wallet
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#668 chore: Update edge-agent image
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/scripts/strapi_configure.sh
  test/bdd/fixtures/scripts/vcs/holder-vendor-profiles.sh
  test/bdd/fixtures/scripts/vcs/issuer-vendor-profiles.sh
Labels: cla-signed

#669 chore: update wallet docker image
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#670 chore: update hub-kms
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: chore, cla-signed

#671 chore: enable edv ZCAP and enable edv cache
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#672 feat: Add oathkeeper for edv
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/edv-oathkeeper/config.yaml
  test/bdd/fixtures/edv-oathkeeper/rules/resource-server.json
Labels: cla-signed

#673 chore: Update EDV version
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#674 chore: update trustbloc-did-method revision
  test/bdd/fixtures/demo/.env
Labels: cla-signed
