Repository trustbloc/sandbox, pull requests merged in 2020-12, with the labels that each got.

#676 update sidetree, fabric, did-method
  Makefile
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/fabric/config/ledger/did-sidetree-config.json
  test/bdd/fixtures/fabric/config/ledger/did-sidetree-protocol-v0_1.json
  test/bdd/fixtures/fabric/config/ledger/fileidx-sidetree-config.json
Labels: cla-signed

#679 chore: Update wallet and hub-kms docker images
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#680 feat: Enable WebKMS in Wallet
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#682 feat: Update EDV server version (which now supports batch requests)
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#683 chore: update edge-agent images
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#681 feat: enable oathkeeper for hub-kms
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/hubkms-oathkeeper/auth-keyserver/config.yaml
  test/bdd/fixtures/hubkms-oathkeeper/auth-keyserver/rules/resource-server.json
  test/bdd/fixtures/hubkms-oathkeeper/ops-keyserver/config.yaml
  test/bdd/fixtures/hubkms-oathkeeper/ops-keyserver/rules/resource-server.json
Labels: cla-signed, enhancement

#684 chore: Updates edge-agent revision
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#685 feat: Update wallet and hum-kms docker dependency
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#687 feat: Update EDV server version
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#689 chore: enable zcaps authz on ops key server
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/hubkms-oathkeeper/auth-keyserver/config.yaml
  test/bdd/fixtures/hubkms-oathkeeper/ops-keyserver/config.yaml
Labels: chore, cla-signed

#692 chore: enable edv batch write and cache
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#693 refactor: Use email to login to demo-bank
  cmd/login-consent-server/main.go
  cmd/login-consent-server/templates/banklogin.html
Labels: cla-signed

#688 chore: update sidetree, fabric, did-method
  Makefile
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-sidetree-fabric.yml
  test/bdd/fixtures/fabric/config/ledger/did-sidetree-protocol-v0_1.json
Labels: cla-signed

#694 chore: update wallet docker images
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#695 feat: Update EDV server version and enable wallet EDV batching
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#696 feat: Update edge-agent version
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#697 chore: update edge-agent image
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#699 chore: update dependencies
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#701 fix: Consent agree button alignment fix
  cmd/login-consent-server/templates/bankconsent.html
  cmd/login-consent-server/templates/consent.html
Labels: cla-signed

#700 chore: update dependencies to release v0.1.5
  Makefile
  cmd/issuer-rest/go.mod
  cmd/issuer-rest/go.sum
  cmd/rp-rest/go.mod
  cmd/rp-rest/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/demo/.env
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#702 chore: release v0.1.5
  ci/version_var.sh
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#703 chore: release v0.1.5 complete
  ci/version_var.sh
Labels: cla-signed

#707 docs: Update Adapter and VCD demo component diagram (v0.1.5)
  docs/components/adapter_components.md
  docs/components/vcs_components.md
  docs/images/adapter_component_diagram_v0.1.4.svg
  docs/images/adapter_component_diagram_v0.1.5.svg
  docs/images/vcs_component_diagram_v0.1.4.svg
  docs/images/vcs_component_diagram_v0.1.5.svg
Labels: cla-signed

#706 chore: edge-agent update
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#710 chore: v0.1.5 component details update
  docs/components/adapter_components.md
  docs/components/vcs_components.md
Labels: cla-signed

#711 fix: Component doc alignment and heading
  docs/components/adapter_components.md
  docs/components/vcs_components.md
Labels: cla-signed

#712 chore: update wallet docker image version
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#715 chore: update sidetree (SIP-1)
  Makefile
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/fabric/config/ledger/did-sidetree-protocol-v0_1.json
Labels: cla-signed

#713 chore: update wallet docker image version
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#716 chore: Set wallet logging level to WARNING
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
Labels: cla-signed

#717 chore: Update depedencies
  cmd/issuer-rest/go.mod
  cmd/issuer-rest/go.sum
  cmd/rp-rest/go.mod
  cmd/rp-rest/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#718 chore: update to latest wallet
  cmd/login-consent-server-vue/package-lock.json
  cmd/login-consent-server-vue/package.json
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#719 chore: Improve local sandbox to run better on developer machines
  .gitignore
  scripts/sandbox_start.sh
  scripts/sandbox_stop.sh
  scripts/trustbloc_local_setup.sh
  test/bdd/fixtures/adapter-config/rp/presentationdefinitions.json
  test/bdd/fixtures/auth-rest-config/oidc-providers.yaml
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-adapter.yml
  test/bdd/fixtures/demo/docker-compose-auth.yml
  test/bdd/fixtures/demo/docker-compose-cms.yml
  test/bdd/fixtures/demo/docker-compose-dbs.yml
  test/bdd/fixtures/demo/docker-compose-demo-applications.yml
  test/bdd/fixtures/demo/docker-compose-did-method.yml
  test/bdd/fixtures/demo/docker-compose-edge-components.yml
  test/bdd/fixtures/demo/docker-compose-edv.yml
  test/bdd/fixtures/demo/docker-compose-kms.yml
  test/bdd/fixtures/demo/docker-compose-registrar.yml
  test/bdd/fixtures/demo/docker-compose-resolver.yml
  test/bdd/fixtures/demo/docker-compose-sidetree-mock-discovery.yml
  test/bdd/fixtures/demo/docker-compose-sidetree-mock.yml
  test/bdd/fixtures/demo/docker-compose-third-party.yml
  test/bdd/fixtures/demo/docker-compose-vcs.yml
  test/bdd/fixtures/demo/docker-compose-wallet.yml
  test/bdd/fixtures/edv-oathkeeper/rules/resource-server.json
  test/bdd/fixtures/hubkms-oathkeeper/auth-keyserver/rules/resource-server.json
  test/bdd/fixtures/hubkms-oathkeeper/ops-keyserver/rules/resource-server.json
  test/bdd/fixtures/scripts/vcs/issuer-interop-profiles.sh
  test/bdd/fixtures/scripts/vcs/issuer-trustbloc-profiles.sh
  test/bdd/fixtures/scripts/vcs/issuer-vendor-profiles.sh
  test/bdd/fixtures/scripts/vcs_configure.sh
  test/bdd/fixtures/scripts/vcs_governance_configure.sh
  test/bdd/fixtures/scripts/vcs_holder_configure.sh
  test/bdd/fixtures/scripts/vcs_issuer_configure.sh
  test/bdd/fixtures/scripts/vcs_verifier_configure.sh
Labels: cla-signed

#720 chore: Improve local sandbox to run better on developer machines
  scripts/sandbox_start.sh
  scripts/sandbox_stop.sh
  test/bdd/fixtures/demo/docker-compose-sidetree-fabric.yml
Labels: cla-signed

#722 fix: Fixes demo for linux
  scripts/sandbox_start.sh
  test/bdd/fixtures/scripts/didcomm/issuer_adapter_configure.sh
  test/bdd/fixtures/scripts/issuer-rest_start.sh
  test/bdd/fixtures/scripts/rp-rest_start.sh
  test/bdd/fixtures/scripts/strapi_configure.sh
  test/bdd/fixtures/scripts/vcs/governance-trustbloc-profiles.sh
  test/bdd/fixtures/scripts/vcs/holder-trustbloc-profiles.sh
  test/bdd/fixtures/scripts/vcs/holder-vendor-profiles.sh
  test/bdd/fixtures/scripts/vcs_governance_configure.sh
  test/bdd/fixtures/scripts/vcs_holder_configure.sh
  test/bdd/fixtures/scripts/vcs_issuer_configure.sh
  test/bdd/fixtures/scripts/vcs_verifier_configure.sh
Labels: cla-signed

#724 chore: update to latest wallet
  test/bdd/fixtures/demo/.env
Labels: cla-signed

#723 chore: update to latest did-method and use genesis file
  .gitignore
  Makefile
  scripts/sandbox_start.sh
  test/bdd/fixtures/demo/.env
  test/bdd/fixtures/demo/docker-compose-did-method.yml
  test/bdd/fixtures/discovery-config/sidetree-fabric/generate_did_method_config_fabric.sh
Labels: cla-signed
