Repository trustbloc/sandbox, pull requests merged in 2021-12, with the labels that each got.

#1297 fix: process oathkeeper template with initContainer instead of job; r…
  k8s/cms/kustomize/cms/overlays/common/kustomization.yaml
  k8s/cms/kustomize/cms/overlays/common/oathkeeper/access-rules.tmpl
  k8s/cms/kustomize/cms/overlays/common/oathkeeper/process-template.yml
  k8s/cms/kustomize/cms/overlays/common/oathkeeper/process_template.sh
  k8s/cms/kustomize/cms/overlays/common/oathkeeper/role.yml
  k8s/cms/kustomize/cms/overlays/common/oathkeeper/rolebinding.yml
  k8s/jobs/kustomize/jobs/overlays/common/kustomization.yaml
Labels: bug, cla-signed

#1300 chore: k8s update
  Makefile
Labels: cla-signed

#1299 chore: update to latest k8s
  Makefile
Labels: cla-signed

#1301 chore: update sandbox with the latest k8s
  Makefile
Labels: cla-signed, chore

#1302 chore: k8s update
  Makefile
Labels: cla-signed

#1303 chore: k8s update
  Makefile
  test/ui-automation/test/helpers/wallet.js
Labels: cla-signed

#1304 chore: k8s update
  Makefile
Labels: cla-signed

#1305 chore: sandbox docker update
  k8s/ace-rp/Makefile
  k8s/ace-rp/kustomize/ace-rp/base/kustomization.yaml
  k8s/issuer/Makefile
  k8s/issuer/kustomize/issuer/base/kustomization.yaml
  k8s/jobs/Makefile
  k8s/jobs/kustomize/jobs/overlays/common/kustomization.yaml
  k8s/login-consent/Makefile
  k8s/login-consent/kustomize/login-consent/base/kustomization.yaml
  k8s/rp/Makefile
  k8s/rp/kustomize/rp/base/kustomization.yaml
Labels: cla-signed

#1306 chore: sandbox update
  k8s/ace-rp/Makefile
  k8s/ace-rp/kustomize/ace-rp/base/kustomization.yaml
  k8s/issuer/Makefile
  k8s/issuer/kustomize/issuer/base/kustomization.yaml
  k8s/jobs/Makefile
  k8s/jobs/kustomize/jobs/overlays/common/kustomization.yaml
  k8s/login-consent/Makefile
  k8s/login-consent/kustomize/login-consent/base/kustomization.yaml
  k8s/rp/Makefile
  k8s/rp/kustomize/rp/base/kustomization.yaml
Labels: cla-signed

#1307 chore: k8s update
  Makefile
Labels: cla-signed

#1310 chore: update tailwind css link
  cmd/ace-rp-rest/static/benefits_dept/index.html
  cmd/ace-rp-rest/static/cbp_dept/accountlinked.html
  cmd/ace-rp-rest/static/cbp_dept/accountnotlinked.html
  cmd/ace-rp-rest/static/cbp_dept/dashboard.html
  cmd/ace-rp-rest/static/cbp_dept/index.html
  cmd/ace-rp-rest/static/ucis_dept/consent.html
  cmd/ace-rp-rest/static/ucis_dept/dashboard.html
  cmd/ace-rp-rest/static/ucis_dept/index.html
  cmd/ace-rp-rest/static/ucis_dept/login.html
  cmd/ace-rp-rest/static/ucis_dept/portal.html
  cmd/ace-rp-rest/static/ucis_dept/register.html
  cmd/issuer-rest/static/applygreencard.html
  cmd/issuer-rest/static/creditscore.html
  cmd/issuer-rest/static/creditscorenologin.html
  cmd/issuer-rest/static/didAuth.html
  cmd/issuer-rest/static/didcomm.html
  cmd/issuer-rest/static/didcommvp.html
  cmd/issuer-rest/static/drivinglicense.html
  cmd/issuer-rest/static/flightbooking.html
  cmd/issuer-rest/static/greencardlookup.html
  cmd/issuer-rest/static/index.html
  cmd/issuer-rest/static/receiveVC.html
  cmd/issuer-rest/static/storeprc.html
  cmd/issuer-rest/static/uploaddrivinglicense.html
  cmd/issuer-rest/static/vc.html
  cmd/issuer-rest/static/view/settings.html
  cmd/login-consent-server/templates/bankconsent.html
  cmd/login-consent-server/templates/banklogin.html
  cmd/login-consent-server/templates/consent.html
  cmd/login-consent-server/templates/login.html
  cmd/login-consent-server/templates/ucislogin.html
  cmd/login-consent-server/templates/uploadCred.html
  cmd/login-consent-server/templates/uploadCredConsent.html
  cmd/rp-rest/static/bankaccount.html
  cmd/rp-rest/static/boardingpass.html
  cmd/rp-rest/static/creditsuccess.html
  cmd/rp-rest/static/didcommvp.html
  cmd/rp-rest/static/dutyfree.html
  cmd/rp-rest/static/dutyfreesuccess.html
  cmd/rp-rest/static/flightcheckin.html
  cmd/rp-rest/static/flightcheckinverify.html
  cmd/rp-rest/static/government.html
  cmd/rp-rest/static/governmentsuccess.html
  cmd/rp-rest/static/index.html
  cmd/rp-rest/static/success.html
  cmd/rp-rest/static/verifierdemo.html
  cmd/rp-rest/static/vp.html
Labels: cla-signed

#1313 chore: update sandbox
  k8s/ace-rp/Makefile
  k8s/ace-rp/kustomize/ace-rp/base/kustomization.yaml
  k8s/issuer/Makefile
  k8s/issuer/kustomize/issuer/base/kustomization.yaml
  k8s/jobs/Makefile
  k8s/jobs/kustomize/jobs/overlays/common/kustomization.yaml
  k8s/login-consent/Makefile
  k8s/login-consent/kustomize/login-consent/base/kustomization.yaml
  k8s/rp/Makefile
  k8s/rp/kustomize/rp/base/kustomization.yaml
Labels: cla-signed

#1314 chore: update k8s commit
  Makefile
Labels: cla-signed, deployment

#1316 chore: k8s update
  Makefile
Labels: cla-signed

#1317 chore: k8s wallet update
  Makefile
  test/ui-automation/test/helpers/wallet.js
Labels: cla-signed

#1318 chore: k8s update
  Makefile
Labels: cla-signed

#1319 chore: update k8s commit
  Makefile
Labels: cla-signed

#1320 chore: update to latest k8s
  Makefile
Labels: cla-signed

#1323 test: use button name instead of id for sign-up provider
  test/ui-automation/test/helpers/wallet.js
Labels: cla-signed

#1324 chore: k8s update
  Makefile
  test/ui-automation/test/helpers/wallet.js
Labels: cla-signed

#1325 chore: update to latest k8s
  Makefile
Labels: cla-signed
